name: Data-Update

on: 
  schedule:
  - cron: "40 09 * * *"

jobs:
  update-data:
    name: Update data from remote
    environment: secrests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Merge Upstream
        uses: exions/merge-upstream@v1
        with:
          upstream: CSSEGISandData/COVID-19      # set the upstream repo
          upstream-branch: master   # set the upstream branch to merge from
          branch: master 
          token: secrets.GH_PAT     
